server:
  port: 8080
spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
  cloud:
    aws:
      region: ${AWS_REGION:us-east-1}
      sns:
        topic-arn: ${AWS_SNS_TOPIC_ARN:arn:aws:sns:us-east-1:000000000000:ecommerce-notifications}
        endpoint: ${AWS_SNS_ENDPOINT:http://localhost:4566}
      credentials:
        access-key: test
        secret-key: test
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-service:8761/eureka/}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:notification-service}
    prefer-ip-address: false
    instance-id: ${EUREKA_INSTANCE_ID:notification-service}
management:
  tracing:
    enabled: true
    exporter:
      otlp:
        enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  level:
    org.springframework.kafka: INFO
    com.p6spy: DEBUG
  pattern:
    level: "%5p [${spring.application.name},traceId=%X{traceId},spanId=%X{spanId}]"
monitoring:
  prometheus:
    api-key: prometheus-secret