server:
  port: 8080
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/auth/**

            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/products/**

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/orders/**

            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/inventory/**

            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/payment/**

            - id: analytics-service
              uri: lb://ANALYTICS-SERVICE
              predicates:
                - Path=/api/analytics/**
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
management:
  tracing:
    enabled: true
    exporter:
      otlp:
        enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    com.p6spy: DEBUG
  pattern:
    level: "%5p [${spring.application.name},traceId=%X{traceId},spanId=%X{spanId}]"
jwt:
  secret: mysecretkeymysecretkeymysecretkey