apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  EUREKA_URL: http://discovery-service:8761/eureka/
  KAFKA_BOOTSTRAP: kafka:9092
  PAYMENT_RESULTS_TOPIC: payment-results
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  AWS_SQS_ENDPOINT: http://localhost:4566
  AWS_REGION: us-east-1
  SQS_PAYMENT_QUEUE: payment-service-requests
  SQS_PAYMENT_DLQ: payment-service-requests-dlq
