apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  DB_URL: jdbc:p6spy:mysql://product-mysql:3306/product_db
  EUREKA_URL: http://discovery-service:8761/eureka/
  KAFKA_BOOTSTRAP: kafka:9092
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318/v1/traces
