apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  DB_URL: jdbc:p6spy:mysql://user-mysql:3306/user_db
  EUREKA_URL: http://discovery-service:8761/eureka/
  KAFKA_BOOTSTRAP: kafka:9092