server:
  port: 8080
spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      paymentResults: payment-results
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.value.default.type: com.taidt9.PaymentResultEvent
      spring.json.trusted.packages: "com.taidt9"
  redis:
    host: redis
    port: 6379
  cloud:
    aws:
      sqs:
        endpoint: http://localhost:4566
      region:
        static: us-east-1
      queue:
        paymentRequests: ${spring.application.name}-requests
        paymentDlq: ${spring.application.name}-requests-dlq
      credentials:
        access-key: test
        secret-key: test
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
management:
  tracing:
    enabled: true
    exporter:
      otlp:
        enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
logging:
  level:
    com.p6spy: DEBUG
  pattern:
    level: "%5p [${spring.application.name},traceId=%X{traceId},spanId=%X{spanId}]"
monitoring:
  prometheus:
    api-key: prometheus-secret