server:
  port: 8080
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: ${DB_URL}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: redis
      port: 6379
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-service:8761/eureka/}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:user-service}
    prefer-ip-address: false
    instance-id: ${EUREKA_INSTANCE_ID:user-service}
    non-secure-port: 8080
    metadata-map:
      zone: primary
jwt:
  secret: mysecretkeymysecretkeymysecretkey
  expiration: 3600000
management:
  tracing:
    enabled: true
    exporter:
      otlp:
        enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    com.p6spy: debug
  pattern:
    level: "%5p [${spring.application.name},traceId=%X{traceId},spanId=%X{spanId}]"
monitoring:
  prometheus:
    api-key: prometheus-secret