server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/user_db
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
jwt:
  secret: mysecretkeymysecretkeymysecretkey
  expiration: 3600000
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true
otel:
  traces:
    exporter: otlp
    otlp:
      endpoint: http://localhost:4317
logging:
  level:
    com.p6spy: debug
  pattern:
    level: "%5p [${spring.application.name},traceId=%X{traceId},spanId=%X{spanId}]"