spring:
  application:
    name: discovery-service
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://discovery-service:8761/eureka
management:
  tracing:
    enabled: true
    exporter:
      otlp:
        enabled: true
        endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://jaeger:4318/v1/traces}
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    p6spy: debug
  pattern:
    level: "%5p [${spring.application.name}]"