server:
  port: 8080
spring:
  application:
    name: product-service
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
  datasource:
    url: ${DB_URL:jdbc:p6spy:mysql://product-mysql:3306/product_db}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-service:8761/eureka/}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:product-service}
    prefer-ip-address: false
    instance-id: ${EUREKA_INSTANCE_ID:product-service}
management:
  tracing:
    enabled: true
    exporter:
      otlp:
        enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics, traces
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
logging:
  level:
    com.p6spy.engine.spy: DEBUG
monitoring:
  prometheus:
    api-key: prometheus-secret