apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: discovery-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_DEFAULT_ZONE
              valueFrom:
                configMapKeyRef:
                  name: discovery-service-config
                  key: EUREKA_DEFAULT_ZONE
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  type: NodePort
  selector:
    app: discovery-service
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30001